#!/bin/bash

get_record_info() {
  domain=$1
  subdomain=$2

  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig +short "$sub.$domain" | awk '{print $1}')
    dest=$(dig +short "$sub.$domain" | awk '{print $2}')

    echo "The subdomain $sub is a $record_type record and points to $dest"
  done
}

get_record_info "$1" "$2"
